// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// PostUpdate Сообщение для обновления сообщения внутри ветки на форуме.
// Пустые параметры остаются без изменений.
//
// swagger:model PostUpdate
type PostUpdate struct {

	// Собственно сообщение форума.
	Message string `json:"message,omitempty"`
}
