// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Status status
// swagger:model Status
type Status struct {

	// Кол-во разделов в базе данных.
	// Required: true
	Forum int64 `json:"forum"`

	// Кол-во сообщений в базе данных.
	// Required: true
	Post int64 `json:"post"`

	// Кол-во веток обсуждения в базе данных.
	// Required: true
	Thread int64 `json:"thread"`

	// Кол-во пользователей в базе данных.
	// Required: true
	User int64 `json:"user"`
}
