// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// UserUpdate Информация о пользователе.
//
// swagger:model UserUpdate
type UserUpdate struct {

	// Описание пользователя.
	About string `json:"about,omitempty"`

	// Почтовый адрес пользователя (уникальное поле).
	// Format: email
	Email strfmt.Email `json:"email,omitempty"`

	// Полное имя пользователя.
	Fullname string `json:"fullname,omitempty"`
}
